<?xml version="1.0"?>
<package format="3">
  <name>vio_nav_stack</name>
  <version>1.0.0</version>
  <description>Vision-Inertial Odometry and AI Obstacle Avoidance for Project Zenith.</description>
  <maintainer email="yogesh@example.com">yogesh</maintainer>
  <license>MIT</license>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
